### ISSUE TITLE
eyelink bug data

### ISSUE THREAD

**Issue by Shadow7912** [Jianshu-L/PreProcess#1]
![Screenshot from 2022-10-10 19-14-19](https://user-images.githubusercontent.com/61609908/194852976-087504df-dae4-4072-a1fd-6bf0ee5d4c48.png)
result/Eyelink 文件夹为空，调试后发现是调用Mousedata时将eyelink data视为bug file，为了排除eyelink data本身问题，用omega的数据跑了一次，发现还是报错。（omega 01-Apr这天是有处理好的眼动数据的，说明眼动数据本身应该没有问题？）

**Comment by Jianshu-L** [comment]
能否把运行的代码发上来，我用omega 01-Apr这天的数据跑RunBEV.m 可以正常运行
<img width="476" alt="Screenshot 2022-10-10 192528" src="https://user-images.githubusercontent.com/43482308/194856056-063004e4-5b90-485d-a124-7c8967828dd7.png">
<img width="441" alt="Screenshot 2022-10-10 192559" src="https://user-images.githubusercontent.com/43482308/194856065-8af3c042-8749-47ee-a01a-84cddae53a71.png">

**Comment by Shadow7912** [comment]
edf 转asc：status = unix(sprintf('edf2asc %s -vel -res', 'omegaL-01-Apr-2021-1.mat'));
处理eyelink：
%% translate Eyelink data
addpath(genpath(("src")));
% create diary
diaryName = sprintf("ppELDiary-%s", date);
eval(sprintf("diary %s",diaryName));
diary on
% process data
mouseData = translateEl(elPath); %#ok<NASGU>
rmpath(genpath(("src")));

**Comment by Jianshu-L** [comment]
edf转asc不能加-vel和-res，会使原始asc多4行数据。

底层代码Eldata中的readASC第212行会reshape成4行的数据，多出的4行会给后续处理带来bug

    data = textscan(C','%f','delimiter', {' ','...'}, ...
        'MultipleDelimsAsOne',true,'TreatAsEmpty','.','EmptyValue',0,'ReturnOnError',false);
    data = reshape(data{1},[4,length(data{1})/4])';

所以截图中会有“Warning: length(data) ~= length(file)”，因为第215行会判断textscan处理会不会改变数据大小

    a = size(C);
    if length(data(:,1)) ~= a(1)
        warning('length(data) ~= length(file)')
    end
